export const SET_BASKET = 'SET_BASKET'
export const EMPTY_BASKET = 'EMPTY_BASKET'
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET'